---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"

exclude_paths: [core/tests/coverage, core/vendor]
