language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
services:
  - mysql
before_script:
  - mysql -e 'create database IF NOT EXISTS esel;'
  - mysql -e 'CREATE TABLE `esel`.`sl_test` (  `id` INT NULL AUTO_INCREMENT,  `data` VARCHAR(45) NULL,  PRIMARY KEY (`id`));'
  - mysql -e 'use esel;'
  - mysql -e 'insert into sl_data values(null,"test")';
