language: php
install:
- cd core
- composer install
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
services:
  - mysql
before_script:
  - mysql -e 'create database IF NOT EXISTS esel;'
  - mysql -e 'CREATE TABLE `esel`.`sl_test` (  `id` INT NULL AUTO_INCREMENT,  `data` VARCHAR(45) NULL,  PRIMARY KEY (`id`));'
  - mysql -e 'insert into `esel`.`sl_test` values(null,"test");'
  - cd ..
 script:
   - phpunit --coverage-clover build/logs/clover.xml
   - CODECLIMATE_REPO_TOKEN=d83a1d4c39f3dffb4ee19512b9d1358dcc91c20778654e5ea3c671043497f467 ./vendor/bin/test-reporter
