// Generated by CoffeeScript 1.10.0
(function() {
  Vue.component('pagination', {
    template: '<div> Page # <input type="number" v-model="page" class="tiny-input"> of {{Math.ceil(count/limit)}} by <input type="number" v-model="limit" class="tiny-input"> </div>',
    props: ['page', 'limit', 'count'],
    watch: {
      page: function(val) {
        if (val <= 0) {
          val = 1;
          this.page = val;
        }
        if (val >= Math.ceil(this.count / this.limit)) {
          val = Math.ceil(this.count / this.limit);
          this.page = val;
        }
        return this.$parent.$emit("pageChanged", val);
      },
      limit: function(val) {
        if (val <= 0) {
          val = 1;
          this.limit = val;
        }
        return this.$parent.$emit("limitChanged", val);
      }
    }
  });

}).call(this);
